### ISSUE TITLE
Initial setup help

### ISSUE THREAD

**Issue by NorskNoobing** [claabs/cs-demo-downloader#1]
I'm not entirely sure how to get the steamguard secret. I have already set up 2fa through ArchiSteamFarm, so I should be able to get the info from there. Maybe you're familiar with ASF, so do you know if they provide the B64 encoded secret, or if it's just the plaintext secret that I'd have to encode myself?

Another thing that would help is to see what the plaintext secret syntax looks like.

**Comment by claabs** [comment]
It should be the 28 character (including the padding `=`) base64 encoded secret. I originally setup ASF with SteamDesktopAuthenticator, so it's the `shared_secret` value from its `.maFile`. Not sure if that can be extracted from an ASF instance.

The value just gets passed in to [steam-totp](https://github.com/DoctorMcKay/node-steam-totp?tab=readme-ov-file#getauthcodesecret-timeoffset-callback), so it could be a hex string as well.

**Comment by NorskNoobing** [comment]
I just copied the `shared_secret` from the `.maFile`. The problem I had was that it was 33 characters, as there's a `+` sign in the value that was converted to `\u002B`. I changed it back to a `+`, and inserted it into the secret field of the json file, and it seems like it's working.

I'm also wondering what's required for the `authCodes` download method? Is it just the `authCodeLogin`, or is the `steamApiKey` also required?

**Comment by claabs** [comment]
The auth code method is useful if you have friends' demos you want to download. The `authCodeLogin` account should ideally be a secondary account, since it has to launch CS2 to get the match data and you don't want it interrupting your main account while in-game. The `steamApiKey` and `authCodes` are also required for that method.

**Comment by NorskNoobing** [comment]
Thanks for the quick response(s). It seems to be up and working now😊
